apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: node-system
  labels:
    run: node-app
spec:
  type: NodePort
  ports:
    - name: dns
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector: 
    run: node-app

