apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: node-system
  labels:
    app: database
spec:
  ports:
    - name: dns
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: database
