apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: node-system
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: cache
        ports:
        - containerPort: 6379
      restartPolicy: Always