apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: node-system
  labels:
    app: redis
spec:
  ports:
    - name: dns
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis